### ISSUE TITLE
inference_detector error

### ISSUE THREAD

**Issue by Yamameeee** [hikvision-research/opera#10]
When I use inference_detector to try PETR, tensor shape error is caused like this:

`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 800, 1067] instead`

How to fix this?

**Comment by Yamameeee** [comment]
Here, `data['img']` is not cast to `DataContainer`.

https://github.com/hikvision-research/opera/blob/33ec0771f2040dabc98512550a17475cffec85c2/opera/apis/inference.py#L196

**Comment by Yamameeee** [comment]
I investigated this problem.
This is caused by `replace_ImageToTensor` in mmdetection.
`replace_ImageToTensor` doesn't deal with `mmdet.ImageToTensor`.

https://github.com/hikvision-research/opera/blob/33ec0771f2040dabc98512550a17475cffec85c2/opera/apis/inference.py#L180

**Comment by shidahu** [comment]
Thanks for your suggestion. We have fixed this issue and you can use inference_detector to try PETR now.
