### ISSUE TITLE
Inference own images

### ISSUE THREAD

**Issue by Riverzxz** [hikvision-research/opera#13]
Hello author, thank you for your contribution. In model inference and testing, the coco dataset is used, and the json file of coco is required, so how can I test and infer my own image? Hope to get your help

**Comment by marsgravity** [comment]
Thanks for your suggestion. We have provided image_demo to infer your own image, and you can use it like `python /opera/demo/image_demo.py ${img_path} /opera/config/petr/petr_r50_16x2_100e_coco.py petr_r50_16x2_100e_coco.pth --out-file ${new_path}`
