### ISSUE TITLE
Why is NMS still being used?

### ISSUE THREAD

**Issue by superaha** [hikvision-research/opera#3]
Hi thanks for sharing the code. In the paper, it is claimed that NMS postprocessing is discarded. However, NMS is being used here:

https://github.com/hikvision-research/opera/blob/0d39963fe5be5224e0ca4fd8ed61860fc515fc68/opera/models/detectors/petr.py#L168

What is the performance gain from NMS?

Thanks

**Comment by shidahu** [comment]
For multi-scale testing, we only utilize NMS to merge the predicted poses from multiple input resolution at a result-level. However, NMS post-processing is discarded in single-scale testing, which is claimed in our paper.
