### ISSUE TITLE
Crowdpose - dataset

### ISSUE THREAD

**Issue by dae-sun** [hikvision-research/opera#4]
Hello! I am reproducing your petr results.
Could you share the weight and evaluation codes for crowdpose dataset?
Thank you.

**Comment by shidahu** [comment]
We will release the code and trained models on CrowdPose dataset as soon as possible.
A few weeks later, thanks.

**Comment by shidahu** [comment]
@dae-sun We have release the code and models for CrowdPose dataset, thanks.
