### ISSUE TITLE
Ask for checkpoints

### ISSUE THREAD

**Issue by lutianhao** [hikvision-research/opera#5]
Hi, I'm going to learn you paper and code, could you please share infos like checkpoints, etc for training and testing? I can not find any address to download checkpoints. Thanks!

**Comment by lutianhao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for your kind response, I've found that. Another question, what is the minimum amount of GPU space required for each model to be used?  
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Dahu ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/29/2022 19:54
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [hikvision-research/opera] Ask for checkpoints (Issue #5)
        
      
    
  
  
We have provided the checkpoints for each algorithm in Opera. The details can be found in configs/xxx/README.md.
Thanks.

**Comment by shidahu** [comment]
Models were trained on NVIDIA Tesla V100 (32G) GPUs by default and a few models (e.g., Swin-L backbone) were trained on NVIDIA Tesla A100 (40G) GPUs.
