### ISSUE TITLE
OKS cost is computed by the normalized groud-truth keypoints

### ISSUE THREAD

**Issue by Nickiris** [hikvision-research/opera#7]
In your hungarian_assigner.py code, the oks cost is computed by the unnormalized groud-truth keypoints. 
However, in your match_cost.py code, the comments in oks cost function show that the groud-truth keypoints are normalized. 
Is the code wrong in hungarian_assigner.py?

**Comment by shidahu** [comment]
Thanks for your question. The comments of OksCost function is wrong and we have revised it.
