### ISSUE TITLE
About 'mmdet.NegLoss'

### ISSUE THREAD

**Issue by Yamameeee** [hikvision-research/opera#9]
For heatmap regression, you use mmdet.NegLoss.
But, I can't find NegLoss in mmdet and mmcv.
Where the NegLoss is defined?

**Comment by shidahu** [comment]
NegLoss is a customed loss function for heatmap regression, as mentioned in CenterNet.
We have wrapped and rename this loss function as CenterFocalLoss.
Please see the latest code. Thanks.
